## **MileStone_1**

Debugging dataset: small enough to test code with; reasonable code should run in 2 minutes

Working dataset:  large enough to do the problem on (training should run no more than 40 minutes)

Convert these datasets to pandas

*   I suggest that you convert datetime to pandas timestamps (allows for time deltas and time manipulation)
*   Pickle (https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.to_pickle.html)  the data.  That converts it to a binary file which can be loaded directly (must faster) into the correct datatypes

## **License**

This program is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.

## **Import Packages & Functions**

In [ ]:
import pandas
from sklearn.model_selection import train_test_split
def getfile(location_pair,**kwargs):
    (loc,gdrive)=location_pair
    loc = 'https://drive.google.com/uc?export=download&id='+gdrive.split('/')[-2]

    #Convert these datasets to pandas
    raw_dataset=pandas.read_csv(loc,**kwargs)
    #Convert datetime to pandas timestamps
    raw_dataset['DATE'] = pandas.to_datetime(raw_dataset['DATE'], format='%Y / %m')

    ## seperate the data by "year"
    split_date = '1992-01-01'
    debugging_dataset = raw_dataset[raw_dataset['DATE'] < split_date] #1990-1991 (2 years)
    debugging_dataset = debugging_dataset.sort_values(by='DATE', ascending=True)
    debugging_dataset = debugging_dataset.reset_index(drop=True) # reset the data index
    working_dataset = raw_dataset[raw_dataset['DATE'] >= split_date] #1992-2023 (~32 years)
    working_dataset = working_dataset.sort_values(by='DATE', ascending=True)
    working_dataset = working_dataset.reset_index(drop=True) # reset the data index

    return raw_dataset, debugging_dataset, working_dataset

# **Import the CSV files**
Load the New York population&weather dataset and tonnage dataset.

In [ ]:
fname_1=("NY_Population_Weather_Data.csv","https://drive.google.com/file/d/1DkB88nrVF2B60Rjxi_7fzRnD31-LUqXH/view?usp=sharing")
fname_2=("NY_Tonnage_Data_v2.csv","https://drive.google.com/file/d/1-57Sr-WC3g5MRxSXCun6HpD-SB1C-B6Q/view?usp=sharing")

raw_dataset_1, debugging_dataset_1, working_dataset_1=getfile(fname_1)
print("raw_dataset_1 dimension:", raw_dataset_1.shape)

raw_dataset_2, debugging_dataset_2, working_dataset_2=getfile(fname_2)
print("raw_dataset_2 dimension:", raw_dataset_2.shape)

raw_dataset_1 dimension: (2023, 11)
raw_dataset_2 dimension: (1983, 9)

### **Merge the debug_dataset:**
small enough to test code with; reasonable code should run in 2 minutes

In [ ]:
debugging_dataset = pandas.merge(debugging_dataset_1, debugging_dataset_2, on=["DATE", "BOROUGH"], how='right')
#debugging_dataset = debugging_dataset.drop(columns=['COMMUNITYDISTRICT','BOROUGH_ID'])

#Pickle the data
debugging_dataset.to_pickle('debugging_dataset.pkl')
debugging_dataset

,DATE,BOROUGH,POPULATION,POPULATION PERCENTAGE,AWND,PRCP,SNOW,TAVG,TMAX,TMIN,TSUN,REFUSETONSCOLLECTED,PAPERTONSCOLLECTED,MGPTONSCOLLECTED,RESORGANICSTONS,SCHOOLORGANICTONS,LEAVESORGANICTONS,XMASTREETONS
0,1990-01-01,Manhattan,1487536,20.31,NaN,135.8,45.0,5.20,8.64,1.75,9018.0,24.4,0.0,0.0,0.0,0.0,0.0,0.0
1,1990-01-01,Queens,1951598,26.65,NaN,135.8,45.0,5.20,8.64,1.75,9018.0,8.4,0.0,0.0,0.0,0.0,0.0,0.0
2,1990-01-01,Staten Island,378977,5.18,NaN,135.8,45.0,5.20,8.64,1.75,9018.0,39.1,0.0,0.0,0.0,0.0,0.0,0.0
3,1990-06-01,Staten Island,378977,5.18,NaN,63.6,0.0,22.28,27.47,17.10,16853.0,11518.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1990-07-01,Staten Island,378977,5.18,NaN,89.2,0.0,24.86,29.28,20.45,12776.0,15243.8,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,1991-12-01,Queens,1951598,26.65,NaN,108.2,18.0,4.20,7.94,0.47,8739.0,63244.4,0.0,0.0,0.0,0.0,0.0,0.0
74,1991-12-01,Bronx,1203789,16.44,NaN,108.2,18.0,4.20,7.94,0.47,8739.0,40642.7,0.0,0.0,0.0,0.0,0.0,0.0
75,1991-12-01,Brooklyn,2300664,31.42,NaN,108.2,18.0,4.20,7.94,0.47,8739.0,74840.8,0.0,0.0,0.0,0.0,0.0,0.0
76,1991-12-01,Manhattan,1487536,20.31,NaN,108.2,18.0,4.20,7.94,0.47,8739.0,46044.1,0.0,0.0,0.0,0.0,0.0,0.0
77,1991-12-01,Staten Island,378977,5.18,NaN,108.2,18.0,4.20,7.94,0.47,8739.0,13576.1,0.0,0.0,0.0,0.0,0.0,0.0

### **Merge the working_dataset:**
large enough to do the problem on (training should run no more than 40 minutes)

In [ ]:
working_dataset = pandas.merge(working_dataset_1, working_dataset_2, on=["DATE", "BOROUGH"], how='right')
#working_dataset = working_dataset.drop(columns=['COMMUNITYDISTRICT','BOROUGH_ID'])
#Pickle the data
working_dataset.to_pickle('working_dataset.pkl')
working_dataset[90:120]

,DATE,BOROUGH,POPULATION,POPULATION PERCENTAGE,AWND,PRCP,SNOW,TAVG,TMAX,TMIN,TSUN,REFUSETONSCOLLECTED,PAPERTONSCOLLECTED,MGPTONSCOLLECTED,RESORGANICSTONS,SCHOOLORGANICTONS,LEAVESORGANICTONS,XMASTREETONS
90,1993-07-01,Bronx,1203789.0,16.44,NaN,43.2,0.0,26.74,32.32,21.15,21423.0,37001.6,1716.7,1695.6,0.0,0.0,0.0,0.0
91,1993-07-01,Brooklyn,2300664.0,31.42,NaN,43.2,0.0,26.74,32.32,21.15,21423.0,74143.6,6199.3,5060.8,0.0,0.0,0.0,0.0
92,1993-07-01,Manhattan,1487536.0,20.31,NaN,43.2,0.0,26.74,32.32,21.15,21423.0,39098.9,4789.7,2477.1,0.0,0.0,0.0,0.0
93,1993-07-01,Queens,1951598.0,26.65,NaN,43.2,0.0,26.74,32.32,21.15,21423.0,69415.1,2243.7,2036.2,0.0,0.0,0.0,0.0
94,1993-07-01,Staten Island,378977.0,5.18,NaN,43.2,0.0,26.74,32.32,21.15,21423.0,15258.1,0.0,29.6,0.0,0.0,0.0,0.0
95,1993-08-01,Bronx,1203789.0,16.44,NaN,137.5,0.0,25.10,30.00,20.20,17164.0,36196.7,1266.5,1148.0,0.0,0.0,0.0,0.0
96,1993-08-01,Brooklyn,2300664.0,31.42,NaN,137.5,0.0,25.10,30.00,20.20,17164.0,72507.6,5558.8,4645.4,0.0,0.0,0.0,0.0
97,1993-08-01,Manhattan,1487536.0,20.31,NaN,137.5,0.0,25.10,30.00,20.20,17164.0,39181.7,4977.7,2096.1,0.0,0.0,0.0,0.0
98,1993-08-01,Queens,1951598.0,26.65,NaN,137.5,0.0,25.10,30.00,20.20,17164.0,68532.6,2279.6,1919.4,0.0,0.0,0.0,0.0
99,1993-08-01,Staten Island,378977.0,5.18,NaN,137.5,0.0,25.10,30.00,20.20,17164.0,14483.3,34.4,10.8,0.0,0.0,0.0,0.0
100,1993-09-01,Staten Island,378977.0,5.18,NaN,133.5,0.0,19.59,23.78,15.41,11597.0,14973.1,75.8,28.9,0.0,0.0,0.0,0.0
101,1993-09-01,Queens,1951598.0,26.65,NaN,133.5,0.0,19.59,23.78,15.41,11597.0,63329.3,4441.2,2668.2,0.0,0.0,0.0,0.0
102,1993-09-01,Brooklyn,2300664.0,31.42,NaN,133.5,0.0,19.59,23.78,15.41,11597.0,73630.8,6327.5,4859.7,0.0,0.0,0.0,0.0
103,1993-09-01,Bronx,1203789.0,16.44,NaN,133.5,0.0,19.59,23.78,15.41,11597.0,35936.2,963.5,759.3,0.0,0.0,0.0,0.0
104,1993-09-01,Manhattan,1487536.0,20.31,NaN,133.5,0.0,19.59,23.78,15.41,11597.0,40823.1,5882.2,2401.2,0.0,0.0,0.0,0.0
105,1993-10-01,Bronx,1203789.0,16.44,NaN,115.4,0.0,13.30,17.50,9.09,12787.0,34535.2,1414.6,1094.0,0.0,0.0,0.0,0.0
106,1993-10-01,Brooklyn,2300664.0,31.42,NaN,115.4,0.0,13.30,17.50,9.09,12787.0,71422.9,6165.7,4596.4,0.0,0.0,0.0,0.0
107,1993-10-01,Manhattan,1487536.0,20.31,NaN,115.4,0.0,13.30,17.50,9.09,12787.0,40068.3,6040.9,2562.4,0.0,0.0,0.0,0.0
108,1993-10-01,Queens,1951598.0,26.65,NaN,115.4,0.0,13.30,17.50,9.09,12787.0,58289.4,6586.2,3920.1,0.0,0.0,0.0,0.0
109,1993-10-01,Staten Island,378977.0,5.18,NaN,115.4,0.0,13.30,17.50,9.09,12787.0,14467.2,65.2,7.2,0.0,0.0,0.0,0.0
110,1993-11-01,Queens,1951598.0,26.65,NaN,55.8,0.0,9.33,13.69,4.98,10606.0,65270.0,6514.8,3940.8,0.0,0.0,0.0,0.0
111,1993-11-01,Bronx,1203789.0,16.44,NaN,55.8,0.0,9.33,13.69,4.98,10606.0,37202.1,1404.6,1137.6,0.0,0.0,0.0,0.0
112,1993-11-01,Brooklyn,2300664.0,31.42,NaN,55.8,0.0,9.33,13.69,4.98,10606.0,75049.3,6067.4,4324.4,0.0,0.0,0.0,0.0
113,1993-11-01,Manhattan,1487536.0,20.31,NaN,55.8,0.0,9.33,13.69,4.98,10606.0,41962.2,5680.5,2265.9,0.0,0.0,0.0,0.0
114,1993-11-01,Staten Island,378977.0,5.18,NaN,55.8,0.0,9.33,13.69,4.98,10606.0,13945.4,2210.0,922.4,0.0,0.0,2736.9,0.0
115,1993-12-01,Staten Island,378977.0,5.18,NaN,125.8,176.0,2.95,6.41,-0.51,8527.0,13090.1,2329.4,996.5,0.0,0.0,685.2,0.0
116,1993-12-01,Manhattan,1487536.0,20.31,NaN,125.8,176.0,2.95,6.41,-0.51,8527.0,41519.0,6396.1,2815.2,0.0,0.0,0.0,0.0
117,1993-12-01,Queens,1951598.0,26.65,NaN,125.8,176.0,2.95,6.41,-0.51,8527.0,55863.7,7056.2,4079.3,0.0,0.0,0.0,0.0
118,1993-12-01,Brooklyn,2300664.0,31.42,NaN,125.8,176.0,2.95,6.41,-0.51,8527.0,73574.7,6859.1,4839.3,0.0,0.0,0.0,0.0
119,1993-12-01,Bronx,1203789.0,16.44,NaN,125.8,176.0,2.95,6.41,-0.51,8527.0,35701.5,1632.0,1395.6,0.0,0.0,0.0,0.0